SEMANTIC_ANTICIPATOR:
  type: 'sem_rgbd'
  resnet_type: 'resnet18'
  unet_nsf: 32
  nclasses: 1
  map_scale: 0.02
  map_size: 251
  imgh: 240
  imgw: 320
  maxmium_object_num: 6
  device: 'cuda:0'
  ckpt: 'ckpt/ckpt_SA_LOC.pt'
  dataset: 'data/eval/dynamic_5scenes_originalModels'
  IF_IM: True # True or False
  freeze_features: False # True or False

OUTPUT_NORMALIZATION:
  channel_0: "sigmoid"
  channel_1: "sigmoid"

IMG_NORMALIZATION:
  res18_img_mean: [0.485, 0.456, 0.406]
  res18_img_std: [0.229, 0.224, 0.225]